function mim_gen_cluster_spec_CL(STUDY,ALLEEG,cluster_dir,save_dir,cluster_to_compute)

    SPEC_PARAMS = struct('freqrange',[1,200],...
        'subject','',...
        'specmode','psd',...
        'freqfac',4,...
        'logtrials','on',...
        'comps','all',...
        'plot_freqrange',[4,60],...
        'plot_ylim',[-35,-8],...
        'subtractsubjectmean','on',...
        'plotmode','normal');
    ERSP_PARAMS = struct('subbaseline','off',...
        'timerange',[],...
        'ersplim',[-2,2],...
        'freqfac',4,...
        'cycles',[3,0.8],...
        'freqrange',[1,200],...
        'plot_freqrange',[4,60],...
        'plot_clim',[-2,2]);
    CLUSTER_PARAMS = struct('algorithm','kmeans',...
        'clust_num',20,...
        'save','off',...
        'filename',[],...
        'filepath',[],...
        'outliers',inf(),...
        'maxiter',200);
    ERSP_STAT_PARAMS = struct('condstats','on',... % ['on'|'off]
        'groupstats','off',... %['on'|'off']
        'method','perm',... % ['param'|'perm'|'bootstrap']
        'singletrials','off',... % ['on'|'off'] load single trials spectral data (if available). Default is 'off'.
        'mode','fieldtrip',... % ['eeglab'|'fieldtrip']
        'fieldtripalpha',0.05,... % [NaN|alpha], Significance threshold (0<alpha<<1)
        'fieldtripmethod','montecarlo',... %[('montecarlo'/'permutation')|'parametric']
        'fieldtripmcorrect','cluster',... %'fdr',...  % ['cluster'|'fdr']
        'fieldtripnaccu',2000);
    STUDY = pop_statparams(STUDY,'condstats',ERSP_STAT_PARAMS.condstats,...
        'groupstats',ERSP_STAT_PARAMS.groupstats,...
        'method',ERSP_STAT_PARAMS.method,...
        'singletrials',ERSP_STAT_PARAMS.singletrials,'mode',ERSP_STAT_PARAMS.mode,...
        'fieldtripalpha',ERSP_STAT_PARAMS.fieldtripalpha,...
        'fieldtripmethod',ERSP_STAT_PARAMS.fieldtripmethod,...
        'fieldtripmcorrect',ERSP_STAT_PARAMS.fieldtripmcorrect,'fieldtripnaccu',ERSP_STAT_PARAMS.fieldtripnaccu);
%     STUDY = pop_erspparams(STUDY,'subbaseline',ERSP_PARAMS.subbaseline,...
%           'ersplim',ERSP_PARAMS.ersplim,'freqrange',ERSP_PARAMS.freqrange,'timerange',ERSP_CROP_TIMES);
    SPEC_PARAMS.subtractsubjectmean = 'on';
    STUDY = pop_specparams(STUDY,'subtractsubjectmean',SPEC_PARAMS.subtractsubjectmean,...
        'freqrange',SPEC_PARAMS.plot_freqrange,'plotmode','condensed',...
        'plotconditions','together','ylim',SPEC_PARAMS.plot_ylim,'plotgroups','together');

    STUDY.currentdesign = 1;
    for i = 1:length(cluster_to_compute)
        save_dir_cluster = [save_dir filesep num2str(cluster_to_compute(i))];
        mkdir(save_dir_cluster)
        fprintf('Computing specdata...%s\n',num2str(cluster_to_compute(i)))
%         tic
%         [STUDY, specdata, specfreqs, pgroup, pcond, pinter] = std_specplot(STUDY, ALLEEG, 'clusters',i,'comps','all','subject','');
%         save(fullfile(save_dir,['readSPEC_', num2str(STUDY.currentdesign),file_keyword,'.mat']), 'specdata', 'specfreqs', 'pgroup', 'pcond', 'pinter');
%         saveas(gcf,fullfile(save_dir,['Design',num2str(TMP_STUDY.currentdesign),file_keyword,'_All_Comps_SPEC.fig']))
%         toc 

        disp('Computing specdata with substract subject mean...')
        tic
        [STUDY2, specdata2, specfreqs2, pgroup2, pcond2, pinter2] = std_specplot(STUDY, ALLEEG, 'clusters',cluster_to_compute(i),'comps','all','subject','','subtractsubjectmean','on');
        save(fullfile(save_dir_cluster,['readSPEC_', num2str(STUDY.currentdesign),STUDY.filename(1:end-6),'_subSubjectMean.mat']), 'specdata2', 'specfreqs2', 'pgroup2', 'pcond2', 'pinter2');
        saveas(gcf,fullfile(save_dir_cluster,['Design',num2str(STUDY.currentdesign),STUDY.filename(1:end-6),'_All_Comps_SPEC_subSubjectMean.fig']))
        toc 
    end
end